author: Mutlu Polatcan
author_email: mutlupolatcan@gmail.com
classifiers:
- 'Programming Language :: Python :: 3.6'
- 'License :: OSI Approved :: Apache Software License'
- 'Operating System :: OS Independent'
description: Zepyhrus is CloudFormation template generator that validates your template
  and inform you easily.
install_requires:
- PyYAML
long_description_content_type: text/markdown
long_description_path: README.md
name: zepyhrus
url: https://github.com/mpolatcan/zepyhrus
version: 0.0.7
