AWSTemplateFormatVersion: ''
Resources:
  EcrTest:
    Properties:
      LifecyclePolicy: {}
      Tags:
      - Key: test1
        Value: test1
      - Key: test2
        Value: test2
    Type: AWS::ECR::Repository
