AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine:
        Fn::Ref: test
      EngineVersion: 5.7.mysql_aurora.2.04.2
      DatabaseName: test-database
    Metadata:
      cluster_name: test
      engine: mysql
    Condition: test
  TestOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      EngineName: test-engine
      MajorEngineVersion: '11.2'
      OptionConfigurations:
      - OptionName: test
      OptionGroupDescription: test-description
    DependsOn:
    - test
  test:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      BasePath: prepend
Parameters:
  TestParameter:
    Type: List<AWS::EC2::SecurityGroup::Id>
    AllowedValues:
    - test1
    - test2
    - test3
Mappings:
  test: {}
Metadata:
  MetadataTest:
    crescent: formation
  AWS::CloudFormation::Authentication:
    CfnAuthenticationTest:
      type: basic
      username: mpolatcan
      password: '12345'
  AWS::CloudFormation::Interface:
    CfnInterfaceTest:
      ParameterGroups:
      - Label:
          default: test
        Parameters:
        - a
        - b
        - c
      ParameterLabels:
      - Label:
          default: test
Outputs:
  OutputTest:
    Description: Output Test Description
    Value: Output Test Value
Conditions:
  ConditionTest:
    Fn::Equals:
    - Fn::Ref: RefTest
    - abc
