AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
  TestOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      EngineName: test-engine
      MajorEngineVersion: '11.2'
      OptionConfigurations:
      - OptionName: test
      OptionGroupDescription: test-description
    DependsOn:
    - test
    Metadata:
      Description: Test description for Crescent
Parameters:
  TestParameter:
    Type: List<AWS::EC2::SecurityGroup::GroupName>
    AllowedValues:
    - test1
    - test2
    - test3
Mappings:
  test:
    a: b
    test: ava
