AWSTemplateFormatVersion: '2010-09-09'
Resources:
  test:
    Properties:
      AssociatedRoles:
      - RoleArn: arnaafaeoea
      Engine: aurora
      EngineMode: serverless
      ScalingConfiguration:
        MaxCapacity: 16
    Type: AWS::RDS::DBCluster
