name: zepyhrus-publish (major)

on:
  push:
    tags:
      - patch

jobs:
  publish:
    name: Zepyhrus major version publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install wheel pyyaml twine
      - run: python version_updater.py major
      - run: python setup.py bdist_wheel
      - run: twine upload dist/*
                --username ${{secrets.PYPI_USERNAME}}
                --password ${{secrets.PYPI_PASSWORD}}
                --non-interactive
