name: zepyhrus-publish

on:
  push:
    tags:
      - patch-*
      - minor-*
      - major-*

jobs:
  publish:
    name: Zepyhrus version publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install wheel pyyaml twine
      - if: contains(github.ref, 'patch')
        run: python version_updater.py patch
      - if: contains(github.ref, 'minor')
        run: python version_updater.py minor
      - if: contains(github.ref, 'major')
        run: python version_updater.py major
      - run: git config user.name 'mpolatcan'
      - run: git config user.email 'mutlupolatcan@gmail.com'
      - run: git add .
      - if: contains(github.ref, 'patch')
        run: git commit -m "new patch version published"
      - if: contains(github.ref, 'minor')
        run: git commit -m "new minor version published"
      - if: contains(github.ref, 'major')
        run: git commit -m "new major version published"
      - run: git push https://${{secrets.GITHUB_TOKEN}}@github.com/mpolatcan/zepyhrus.git HEAD:master
      - run: python setup.py bdist_wheel
      - run: twine upload dist/*
                --username ${{secrets.PYPI_USERNAME}}
                --password ${{secrets.PYPI_PASSWORD}}
                --non-interactive